cors:
  allow_origins: ["*"]
  allow_methods: [GET, POST, PUT]
  allow_headers: ["Content-Type, Authorization"]
  expose_headers: ["Content-Type, Authorization"]

db:
  host: db
  user: project
  password: project123
  db_name: project_db
  port: 5432

app:
  mode: debug
  port: 8080